#!/usr/bin/perl -w

use utf8;

use LWP::Simple;

binmode(STDOUT, ":utf8");

$path = "zuiltext";

open (MYFILE, ">:encoding(UTF-8)", $path);

	
	my $content = get("http://infozuil.stickyutrecht.nl/text.php");
	die "Couldn't get it!" unless defined $content;
	print MYFILE $content;
	print $content;

close (MYFILE);

print "\ngetStickyunit done\n\n";
